import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { cn }from "@/lib/utils";
import { ThemeProvider } from "@/components/ui/ThemeProvider";

const fontNotoSansJP = Noto_Sans_JP ({ subsets:["latin"]});

export const metadata: Metadata = {
  title: "post writer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
         className={cn(
          "bg-background antialiased min-h-screen",
          fontNotoSansJP.className
        )}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>


        {children}
      </body>
    </html>
  );
}
